### ISSUE TITLE
17/02/2020 Improvements.

### ISSUE THREAD

**Issue by Neo6666666** [DOXOPOKC/accountant_app#34]
Дата начала оказания услуг, Конечная дата оказания услуг, Норматив и Количественный показатель - сделать проверку на null для всех 4 полей. Сделать их обязательными полями.
Русифицировать календарь и сделать нормальное отображение (дд.мм.гггг).
Сделать Уполномоченное лицо по аналогии с нормативами.

В пакете вывести название контрагента вместо id. Или id самого пакета.

**Comment by DOXOPOKC** [comment]
FIx data in packages
